import {Inter} from 'next/font/google';
import "../globals.css";
import ToasterContext from '@components/ToasterContext';
import Provider from '@components/Provider';
import TopBar from '@components/TopBar';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Mess Chat App',
  description: "Generated by Create Next App",
}

export default function RootLayer({children}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-2`}>
        <ToasterContext/>
        <Provider>
          <TopBar/> 
          {children}
        </Provider>
      </body>
    </html>
  )
}
