import {Inter} from 'next/font/google';
import "../globals.css";
import ToasterContext from '@components/ToasterContext';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Mess Chat App',
  description: "Generated by Create Next App",
}

export default function RootLayer({children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext/>
        {children}
      </body>
    </html>
  )
}
